### ISSUE TITLE
Healing with Poultice does not work in newest update

### ISSUE THREAD

**Issue by MaverickX7** [LeandroTheDev/level_up#11]
In singleplayer, attempting to heal with a poultice does nothing and consumes the item. I rolled back the mod to 1.1.5 and I could heal again. Haven't tested with other healing items. I still regenerate health naturally.

**Comment by LeandroTheDev** [comment]
LevelUP doesn't change anything with healing items or healing effectiveness from items, i tested in single player and dedicated server on version ``1.1.8-pre.2`` working normally, can you provide me the logs file to try understand what is happening?

**Comment by MaverickX7** [comment]
[client-main.txt](https://github.com/LeandroTheDev/level_up/files/15238648/client-main.txt)

After looking at this file it seems like it might be registering as damage? Not experienced much in reading logs, but it seems like the armor I am wearing is reducing what it calls damage whenever I try to heal.

**Comment by MaverickX7** [comment]
Had to take off my armor AND clothes, but after doing so the poultice does heal me. The logs say my leather armor level is preventing the "Damage"

**Comment by LeandroTheDev** [comment]
Very strange... how the function receiveDamage from leather armors is blocking the healing from poultice? 
I need to investigate this better

**Comment by LeandroTheDev** [comment]
Coincidentally the problem is already solved in this [issue](https://github.com/LeandroTheDev/level_up/issues/10), in version 1.1.8 full release, when you heal with poultice the receiveDamage function is called with the actual heal amount as the damage (why?), and the LevelUP doens't handle that in 1.1.8-pre.2, what happens is the leather armor reduces the "damage" received so every level you have with the armor you receive less heals and it gets to a point where you just heal nothing.
